doc: Fixes Debian dependencies for Python
Debian Sid switched to Python 3.7 . Make the dependencies more future-proof.

Fixes python-libvirt build:
> libvirt-override.c:20:10: fatal error: Python.h: No such file or directory
>  #include <Python.h>
>           ^~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Change-Id: I730a5187f57fab24cf945fa428753a9b7da12765
Signed-off-by: Mickaël Salaün <mickael.salaun@ssi.gouv.fr>